# Generated by Django 3.1 on 2021-05-25 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0002_auto_20210525_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uuid',
            old_name='uuid',
            new_name='c_uuid',
        ),
    ]
