# Generated by Django 3.1 on 2021-05-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0003_auto_20210525_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uuid',
            old_name='c_uuid',
            new_name='uuid',
        ),
    ]
