# Generated by Django 3.1 on 2021-05-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_api', '0004_auto_20210525_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuid',
            name='uuid',
            field=models.UUIDField(),
        ),
    ]
